### ISSUE TITLE
New version on PyPI

### ISSUE THREAD

**Issue by heston** [gregorynicholas/flask-xsrf#4]
Looks like the last version in PyPI is 1.0.1 from 2013. There have been a few important changes since then. Any chance we could get a new release?

Thanks!

**Comment by gregorynicholas** [comment]
@heston -  yes ill push a new version to pypi now

**Comment by gregorynicholas** [comment]
@heston 
- pypi: https://pypi.python.org/pypi/flask-xsrf/1.0.2  (apologies / LULZ @ the formatting..)
- release-tag: https://github.com/gregorynicholas/flask-xsrf/releases/tag/1.0.2

**Comment by heston** [comment]
@gregorynicholas Awesome, thanks!
