### ISSUE TITLE
Actually publish 1.0.3 to pypi

### ISSUE THREAD

**Issue by asottile** [gregorynicholas/flask-xsrf#9]
Thanks for bumping the version number :D -- can this be uploaded to pypi as well?

**Comment by gregorynicholas** [comment]
hey man, apologies for the issues & delay on this. pypi has made some updates to their publishing flow, seems i have to take another pass on submitting the release

**Comment by asottile** [comment]
Ah yeah, here's the easiest way to do this now:

1. set up a `~/.pypirc`.  Here's the one I use [asottile/scratch:.pypirc](https://github.com/asottile/scratch/blob/master/.pypirc)
2. Create the distributions: `python setup.py sdist bdist_wheel`
3. Install twine (I use a virtualenv, `pip install --user twine` is probably another option)
4. `twine upload --repository pypi --skip-existing dist/*`

**Comment by asottile** [comment]
any updates on this? :)

**Comment by asottile** [comment]
@gregorynicholas ping!

**Comment by asottile** [comment]
I no longer need this, we ended up factoring it out
